#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAFIA_REPO == "shinchanbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NoaW5jaGFuNzIyMi9TaGluY2hhbk9QL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $MAFIA_REPO == "MAFIABOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NoaW5jaGFuNzIyMi9TaGluY2hhbk9QL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $MAFIA_REPO =~ $regex ]]
    then
        if [[ $MAFIA_REPO_BRANCH ]]
        then
            echo "${MAFIA_REPO}/archive/${MAFIA_REPO_BRANCH}.zip"
        else
            echo "${MAFIA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1NoaW5jaGFuNzIyMi9TaGluY2hhbk9QL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    Starting ShinchanBot    "
    echo "
‌‌‎           ____  _   _ ___ _   _  ____ _   _    _    _   _ 
          / ___|| | | |_ _| \ | |/ ___| | | |  / \  | \ | |
          \___ \| |_| || ||  \| | |   | |_| | / _ \ |  \| |
           ___) |  _  || || |\  | |___|  _  |/ ___ \| |\  |
          |____/|_| |_|___|_| \_|\____|_| |_/_/   \_\_| \_|
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
